<#
================================================================================
 Active Directory Certificate Services (AD CS) ESC1 Automated Remediation Script
 Target Domain : invictus.local
 Generated On  : 2026-09-27 13:32:38
 Generated By  : ADCS ESC1 Vulnerability Scanner (Author: Oussama Belhane)
 MITRE ATT&CK  : T1649 - Steal or Forge Authentication Certificates
================================================================================
 INSTRUCTIONS:
 1. Execute this script with Domain Admin privileges on a DC or host with RSAT.
 2. Automatic XML backups are created before any changes are applied.
 3. The script strips CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT (0x1) to prevent SAN spoofing.
================================================================================
#>

#Requires -RunAsAdministrator

Import-Module ActiveDirectory -ErrorAction Stop

$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$backupDir = Join-Path $PWD "ADCS_Remediation_Backup_$timestamp"
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
Write-Host "[*] AD CS ESC1 Remediation started for: invictus.local" -ForegroundColor Cyan
Write-Host "[*] Automated backups will be saved to: $backupDir`n" -ForegroundColor Yellow

$configDN = (Get-ADRootDSE).configurationNamingContext
$templatesBase = "CN=Certificate Templates,CN=Public Key Services,CN=Services,$configDN"

# -------------------------------------------------------------------------
# Remediation for Vulnerable Template: SubCA ('Subordinate Certification Authority')
# -------------------------------------------------------------------------
Write-Host "[*] Hardening template: SubCA..." -ForegroundColor Cyan
$targetDN = "CN=SubCA,$templatesBase"
$obj = Get-ADObject -Identity $targetDN -Properties 'msPKI-Certificate-Name-Flag', 'msPKI-Enrollment-Flag'
if ($obj) {
    # Step 1: Export backup prior to modification
    $backupFile = Join-Path $backupDir "SubCA_backup.clixml"
    $obj | Export-Clixml -Path $backupFile
    Write-Host "  ├── [BACKUP] Saved existing object to $backupFile" -ForegroundColor Gray

    # Step 2: Clear CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT (0x00000001)
    $curFlag = [int]($obj.'msPKI-Certificate-Name-Flag')
    $newFlag = $curFlag -band (-bnot 0x1)
    Set-ADObject -Identity $targetDN -Replace @{'msPKI-Certificate-Name-Flag' = $newFlag}
    Write-Host "  ├── [REMEDIATED] Removed Enrollee Supplies SAN flag." -ForegroundColor Green
    Write-Host "  │   Flag Transition: 0x$($curFlag.ToString('X8')) -> 0x$($newFlag.ToString('X8'))" -ForegroundColor DarkGreen

    # Step 3: Verification
    $verifiedObj = Get-ADObject -Identity $targetDN -Properties 'msPKI-Certificate-Name-Flag'
    $verifiedFlag = [int]($verifiedObj.'msPKI-Certificate-Name-Flag')
    if (($verifiedFlag -band 0x1) -eq 0) {
        Write-Host "  └── [VERIFIED] Template SubCA is now secure against ESC1!" -ForegroundColor Green
    } else {
        Write-Host "  └── [WARNING] Verification failed for SubCA. Check permissions!" -ForegroundColor Red
    }
}

# -------------------------------------------------------------------------
# Remediation for Vulnerable Template: ESC1-Vulnerable ('ESC1-Vulnerable')
# -------------------------------------------------------------------------
Write-Host "[*] Hardening template: ESC1-Vulnerable..." -ForegroundColor Cyan
$targetDN = "CN=ESC1-Vulnerable,$templatesBase"
$obj = Get-ADObject -Identity $targetDN -Properties 'msPKI-Certificate-Name-Flag', 'msPKI-Enrollment-Flag'
if ($obj) {
    # Step 1: Export backup prior to modification
    $backupFile = Join-Path $backupDir "ESC1-Vulnerable_backup.clixml"
    $obj | Export-Clixml -Path $backupFile
    Write-Host "  ├── [BACKUP] Saved existing object to $backupFile" -ForegroundColor Gray

    # Step 2: Clear CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT (0x00000001)
    $curFlag = [int]($obj.'msPKI-Certificate-Name-Flag')
    $newFlag = $curFlag -band (-bnot 0x1)
    Set-ADObject -Identity $targetDN -Replace @{'msPKI-Certificate-Name-Flag' = $newFlag}
    Write-Host "  ├── [REMEDIATED] Removed Enrollee Supplies SAN flag." -ForegroundColor Green
    Write-Host "  │   Flag Transition: 0x$($curFlag.ToString('X8')) -> 0x$($newFlag.ToString('X8'))" -ForegroundColor DarkGreen

    # Step 3: Verification
    $verifiedObj = Get-ADObject -Identity $targetDN -Properties 'msPKI-Certificate-Name-Flag'
    $verifiedFlag = [int]($verifiedObj.'msPKI-Certificate-Name-Flag')
    if (($verifiedFlag -band 0x1) -eq 0) {
        Write-Host "  └── [VERIFIED] Template ESC1-Vulnerable is now secure against ESC1!" -ForegroundColor Green
    } else {
        Write-Host "  └── [WARNING] Verification failed for ESC1-Vulnerable. Check permissions!" -ForegroundColor Red
    }
}

Write-Host "[✔] All remediation actions applied. Active Directory replication initiated." -ForegroundColor Green
Write-Host "[*] To apply immediately on CA hosts, optionally run: Restart-Service CertSvc`n" -ForegroundColor Yellow