"""
Automated PowerShell Remediation Script Generator
Generates production-grade PowerShell scripts to strip CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
with automatic CLIXML backups.
"""

from datetime import datetime
from colorama import Fore, Style


def generate_remediation_script(active_vulns, domain, output_file="remediate_esc1.ps1"):
    """
    Generates a production-ready, safety-checked PowerShell script
    for Active Directory administrators to remediate detected ESC1 vulnerabilities.
    """
    if not active_vulns:
        print(Fore.YELLOW + "[*] No active ESC1 vulnerabilities to remediate.")
        return None

    lines = [
        "<#",
        "=" * 80,
        " Active Directory Certificate Services (AD CS) ESC1 Automated Remediation Script",
        f" Target Domain : {domain}",
        f" Generated On  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        " Generated By  : ADCS ESC1 Vulnerability Scanner (Author: Oussama Belhane)",
        " MITRE ATT&CK  : T1649 - Steal or Forge Authentication Certificates",
        "=" * 80,
        " INSTRUCTIONS:",
        " 1. Execute this script with Domain Admin privileges on a DC or host with RSAT.",
        " 2. Automatic XML backups are created before any changes are applied.",
        " 3. The script strips CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT (0x1) to prevent SAN spoofing.",
        "=" * 80,
        "#>",
        "",
        "#Requires -RunAsAdministrator",
        "",
        "Import-Module ActiveDirectory -ErrorAction Stop",
        "",
        "$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'",
        "$backupDir = Join-Path $PWD \"ADCS_Remediation_Backup_$timestamp\"",
        "New-Item -ItemType Directory -Path $backupDir -Force | Out-Null",
        f"Write-Host \"[*] AD CS ESC1 Remediation started for: {domain}\" -ForegroundColor Cyan",
        "Write-Host \"[*] Automated backups will be saved to: $backupDir`n\" -ForegroundColor Yellow",
        "",
        "$configDN = (Get-ADRootDSE).configurationNamingContext",
        "$templatesBase = \"CN=Certificate Templates,CN=Public Key Services,CN=Services,$configDN\"",
        ""
    ]

    for vuln in active_vulns:
        name = vuln["name"]
        display = vuln.get("display_name", name)
        lines.extend([
            f"# -------------------------------------------------------------------------",
            f"# Remediation for Vulnerable Template: {name} ('{display}')",
            f"# -------------------------------------------------------------------------",
            f"Write-Host \"[*] Hardening template: {name}...\" -ForegroundColor Cyan",
            f"$targetDN = \"CN={name},$templatesBase\"",
            f"$obj = Get-ADObject -Identity $targetDN -Properties 'msPKI-Certificate-Name-Flag', 'msPKI-Enrollment-Flag'",
            f"if ($obj) {{",
            f"    # Step 1: Export backup prior to modification",
            f"    $backupFile = Join-Path $backupDir \"{name}_backup.clixml\"",
            f"    $obj | Export-Clixml -Path $backupFile",
            f"    Write-Host \"  ├── [BACKUP] Saved existing object to $backupFile\" -ForegroundColor Gray",
            f"",
            f"    # Step 2: Clear CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT (0x00000001)",
            f"    $curFlag = [int]($obj.'msPKI-Certificate-Name-Flag')",
            f"    $newFlag = $curFlag -band (-bnot 0x1)",
            f"    Set-ADObject -Identity $targetDN -Replace @{{'msPKI-Certificate-Name-Flag' = $newFlag}}",
            f"    Write-Host \"  ├── [REMEDIATED] Removed Enrollee Supplies SAN flag.\" -ForegroundColor Green",
            f"    Write-Host \"  │   Flag Transition: 0x$($curFlag.ToString('X8')) -> 0x$($newFlag.ToString('X8'))\" -ForegroundColor DarkGreen",
            f"",
            f"    # Step 3: Verification",
            f"    $verifiedObj = Get-ADObject -Identity $targetDN -Properties 'msPKI-Certificate-Name-Flag'",
            f"    $verifiedFlag = [int]($verifiedObj.'msPKI-Certificate-Name-Flag')",
            f"    if (($verifiedFlag -band 0x1) -eq 0) {{",
            f"        Write-Host \"  └── [VERIFIED] Template {name} is now secure against ESC1!\" -ForegroundColor Green",
            f"    }} else {{",
            f"        Write-Host \"  └── [WARNING] Verification failed for {name}. Check permissions!\" -ForegroundColor Red",
            f"    }}",
            f"}}",
            ""
        ])

    lines.extend([
        "Write-Host \"[✔] All remediation actions applied. Active Directory replication initiated.\" -ForegroundColor Green",
        "Write-Host \"[*] To apply immediately on CA hosts, optionally run: Restart-Service CertSvc`n\" -ForegroundColor Yellow"
    ])

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(Fore.GREEN + Style.BRIGHT + f"[+] Hardened PowerShell remediation script generated: {output_file}")
    return output_file
